
export const AuthErrors = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  PASSWORD_NOT_MATCH: 'PASSWORD_NOT_MATCH',
  NO_CHANGES_MADE: 'NO_CHANGES_MADE',
};

