export const AWS_ERRORS = {
  MISSING_AWS_ENV_VARIABLES: 'MISSING_AWS_ENV_VARIABLES',
  FAILED_TO_UPLOAD_MEDIA_FILE: 'FAILED_TO_UPLOAD_MEDIA_FILE',
  FAILED_TO_DELETE_MEDIA_FILE: 'FAILED_TO_DELETE_MEDIA_FILE',
  FILE_DELETED_SUCCESSFULLY: 'FILE_DELETED_SUCCESSFULLY',
};
