export const GlobalErrors = {
  UNKNOWN_ERROR: 'UNKNOWN ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL SERVER ERROR',
  NOT_FOUND: 'NOT FOUND',
  BAD_REQUEST: 'BAD REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
};
